class_name SFErrorCodes
extends RefCounted

enum Code {
	UNKNOWN = -1,
	NONE = 0,
	UNAUTHORIZED,
	INVALID_TOKEN,
	AUTHENTICATION_REQUIRED,
	INVALID_APP_ID,
	APP_ID_EXPIRED,
	APP_ID_REVOKED,
	APP_ID_SUSPENDED,
	MISSING_APP_ID,
	AUTHENTICATION_TIMEOUT,
	SDK_VERSION_UNSUPPORTED,
	UNSUPPORTED_GAME_DATA_FORMAT,
	INVALID_INPUT,
	INVALID_GAME_NAME,
	INVALID_ROOM_CODE,
	INVALID_PLAYER_NAME,
	INVALID_MAX_PLAYERS,
	MESSAGE_TOO_LARGE,
	ROOM_NOT_FOUND,
	ROOM_FULL,
	ALREADY_IN_ROOM,
	NOT_IN_ROOM,
	ROOM_CREATION_FAILED,
	MAX_ROOMS_PER_GAME_EXCEEDED,
	INVALID_ROOM_STATE,
	AUTHORITY_NOT_SUPPORTED,
	AUTHORITY_CONFLICT,
	AUTHORITY_DENIED,
	RATE_LIMIT_EXCEEDED,
	TOO_MANY_CONNECTIONS,
	RECONNECTION_FAILED,
	RECONNECTION_TOKEN_INVALID,
	RECONNECTION_EXPIRED,
	PLAYER_ALREADY_CONNECTED,
	SPECTATOR_NOT_ALLOWED,
	TOO_MANY_SPECTATORS,
	NOT_A_SPECTATOR,
	SPECTATOR_JOIN_FAILED,
	INTERNAL_ERROR,
	STORAGE_ERROR,
	SERVICE_UNAVAILABLE,
	DATABASE_ERROR,
}

const _CODE_TO_STRING: Dictionary = {
	Code.NONE: "",
	Code.UNAUTHORIZED: "UNAUTHORIZED",
	Code.INVALID_TOKEN: "INVALID_TOKEN",
	Code.AUTHENTICATION_REQUIRED: "AUTHENTICATION_REQUIRED",
	Code.INVALID_APP_ID: "INVALID_APP_ID",
	Code.APP_ID_EXPIRED: "APP_ID_EXPIRED",
	Code.APP_ID_REVOKED: "APP_ID_REVOKED",
	Code.APP_ID_SUSPENDED: "APP_ID_SUSPENDED",
	Code.MISSING_APP_ID: "MISSING_APP_ID",
	Code.AUTHENTICATION_TIMEOUT: "AUTHENTICATION_TIMEOUT",
	Code.SDK_VERSION_UNSUPPORTED: "SDK_VERSION_UNSUPPORTED",
	Code.UNSUPPORTED_GAME_DATA_FORMAT: "UNSUPPORTED_GAME_DATA_FORMAT",
	Code.INVALID_INPUT: "INVALID_INPUT",
	Code.INVALID_GAME_NAME: "INVALID_GAME_NAME",
	Code.INVALID_ROOM_CODE: "INVALID_ROOM_CODE",
	Code.INVALID_PLAYER_NAME: "INVALID_PLAYER_NAME",
	Code.INVALID_MAX_PLAYERS: "INVALID_MAX_PLAYERS",
	Code.MESSAGE_TOO_LARGE: "MESSAGE_TOO_LARGE",
	Code.ROOM_NOT_FOUND: "ROOM_NOT_FOUND",
	Code.ROOM_FULL: "ROOM_FULL",
	Code.ALREADY_IN_ROOM: "ALREADY_IN_ROOM",
	Code.NOT_IN_ROOM: "NOT_IN_ROOM",
	Code.ROOM_CREATION_FAILED: "ROOM_CREATION_FAILED",
	Code.MAX_ROOMS_PER_GAME_EXCEEDED: "MAX_ROOMS_PER_GAME_EXCEEDED",
	Code.INVALID_ROOM_STATE: "INVALID_ROOM_STATE",
	Code.AUTHORITY_NOT_SUPPORTED: "AUTHORITY_NOT_SUPPORTED",
	Code.AUTHORITY_CONFLICT: "AUTHORITY_CONFLICT",
	Code.AUTHORITY_DENIED: "AUTHORITY_DENIED",
	Code.RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
	Code.TOO_MANY_CONNECTIONS: "TOO_MANY_CONNECTIONS",
	Code.RECONNECTION_FAILED: "RECONNECTION_FAILED",
	Code.RECONNECTION_TOKEN_INVALID: "RECONNECTION_TOKEN_INVALID",
	Code.RECONNECTION_EXPIRED: "RECONNECTION_EXPIRED",
	Code.PLAYER_ALREADY_CONNECTED: "PLAYER_ALREADY_CONNECTED",
	Code.SPECTATOR_NOT_ALLOWED: "SPECTATOR_NOT_ALLOWED",
	Code.TOO_MANY_SPECTATORS: "TOO_MANY_SPECTATORS",
	Code.NOT_A_SPECTATOR: "NOT_A_SPECTATOR",
	Code.SPECTATOR_JOIN_FAILED: "SPECTATOR_JOIN_FAILED",
	Code.INTERNAL_ERROR: "INTERNAL_ERROR",
	Code.STORAGE_ERROR: "STORAGE_ERROR",
	Code.SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
	Code.DATABASE_ERROR: "DATABASE_ERROR",
}

const _STRING_TO_CODE: Dictionary = {
	"UNAUTHORIZED": Code.UNAUTHORIZED,
	"INVALID_TOKEN": Code.INVALID_TOKEN,
	"AUTHENTICATION_REQUIRED": Code.AUTHENTICATION_REQUIRED,
	"INVALID_APP_ID": Code.INVALID_APP_ID,
	"APP_ID_EXPIRED": Code.APP_ID_EXPIRED,
	"APP_ID_REVOKED": Code.APP_ID_REVOKED,
	"APP_ID_SUSPENDED": Code.APP_ID_SUSPENDED,
	"MISSING_APP_ID": Code.MISSING_APP_ID,
	"AUTHENTICATION_TIMEOUT": Code.AUTHENTICATION_TIMEOUT,
	"SDK_VERSION_UNSUPPORTED": Code.SDK_VERSION_UNSUPPORTED,
	"UNSUPPORTED_GAME_DATA_FORMAT": Code.UNSUPPORTED_GAME_DATA_FORMAT,
	"INVALID_INPUT": Code.INVALID_INPUT,
	"INVALID_GAME_NAME": Code.INVALID_GAME_NAME,
	"INVALID_ROOM_CODE": Code.INVALID_ROOM_CODE,
	"INVALID_PLAYER_NAME": Code.INVALID_PLAYER_NAME,
	"INVALID_MAX_PLAYERS": Code.INVALID_MAX_PLAYERS,
	"MESSAGE_TOO_LARGE": Code.MESSAGE_TOO_LARGE,
	"ROOM_NOT_FOUND": Code.ROOM_NOT_FOUND,
	"ROOM_FULL": Code.ROOM_FULL,
	"ALREADY_IN_ROOM": Code.ALREADY_IN_ROOM,
	"NOT_IN_ROOM": Code.NOT_IN_ROOM,
	"ROOM_CREATION_FAILED": Code.ROOM_CREATION_FAILED,
	"MAX_ROOMS_PER_GAME_EXCEEDED": Code.MAX_ROOMS_PER_GAME_EXCEEDED,
	"INVALID_ROOM_STATE": Code.INVALID_ROOM_STATE,
	"AUTHORITY_NOT_SUPPORTED": Code.AUTHORITY_NOT_SUPPORTED,
	"AUTHORITY_CONFLICT": Code.AUTHORITY_CONFLICT,
	"AUTHORITY_DENIED": Code.AUTHORITY_DENIED,
	"RATE_LIMIT_EXCEEDED": Code.RATE_LIMIT_EXCEEDED,
	"TOO_MANY_CONNECTIONS": Code.TOO_MANY_CONNECTIONS,
	"RECONNECTION_FAILED": Code.RECONNECTION_FAILED,
	"RECONNECTION_TOKEN_INVALID": Code.RECONNECTION_TOKEN_INVALID,
	"RECONNECTION_EXPIRED": Code.RECONNECTION_EXPIRED,
	"PLAYER_ALREADY_CONNECTED": Code.PLAYER_ALREADY_CONNECTED,
	"SPECTATOR_NOT_ALLOWED": Code.SPECTATOR_NOT_ALLOWED,
	"TOO_MANY_SPECTATORS": Code.TOO_MANY_SPECTATORS,
	"NOT_A_SPECTATOR": Code.NOT_A_SPECTATOR,
	"SPECTATOR_JOIN_FAILED": Code.SPECTATOR_JOIN_FAILED,
	"INTERNAL_ERROR": Code.INTERNAL_ERROR,
	"STORAGE_ERROR": Code.STORAGE_ERROR,
	"SERVICE_UNAVAILABLE": Code.SERVICE_UNAVAILABLE,
	"DATABASE_ERROR": Code.DATABASE_ERROR,
}


static func from_string(error_code: Variant) -> int:
	if error_code == null:
		return Code.NONE
	if typeof(error_code) != TYPE_STRING:
		return Code.UNKNOWN
	if error_code.is_empty():
		return Code.NONE
	return int(_STRING_TO_CODE.get(error_code, Code.UNKNOWN))


static func to_wire_string(error_code: int) -> String:
	if error_code == Code.UNKNOWN:
		return "UNKNOWN"
	return String(_CODE_TO_STRING.get(error_code, "UNKNOWN"))


static func is_known(error_code: Variant) -> bool:
	return typeof(error_code) == TYPE_STRING and _STRING_TO_CODE.has(error_code)


static func category(error_code: int) -> String:
	if error_code == Code.NONE:
		return "none"
	if error_code >= Code.UNAUTHORIZED and error_code <= Code.UNSUPPORTED_GAME_DATA_FORMAT:
		return "authentication"
	if error_code >= Code.INVALID_INPUT and error_code <= Code.MESSAGE_TOO_LARGE:
		return "validation"
	if error_code >= Code.ROOM_NOT_FOUND and error_code <= Code.INVALID_ROOM_STATE:
		return "room"
	if error_code >= Code.AUTHORITY_NOT_SUPPORTED and error_code <= Code.AUTHORITY_DENIED:
		return "authority"
	if error_code >= Code.RATE_LIMIT_EXCEEDED and error_code <= Code.TOO_MANY_CONNECTIONS:
		return "ratelimit"
	if error_code >= Code.RECONNECTION_FAILED and error_code <= Code.PLAYER_ALREADY_CONNECTED:
		return "reconnection"
	if error_code >= Code.SPECTATOR_NOT_ALLOWED and error_code <= Code.SPECTATOR_JOIN_FAILED:
		return "spectator"
	if error_code >= Code.INTERNAL_ERROR and error_code <= Code.DATABASE_ERROR:
		return "server"
	return "unknown"
